# client/Dockerfile.dev
# Dockerfile для режима разработки клиента (с Hot-Reload)
FROM node:18-alpine

WORKDIR /app

# Копируем только package.json для кэширования установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной код.
# Файлы будут обновляться через volume mount, но это нужно для первоначального состояния.
COPY . .

# Открываем порт, который использует Vite dev server
EXPOSE 3000

# Команда для запуска dev-сервера.
# Он будет слушать на всех интерфейсах внутри контейнера.
CMD ["npm", "run", "dev"]