services:
  client: # Сервис фронтенда
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  api: # Сервис бэкенда
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./api/.env
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/mutabor?schema=public
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mutabor
    volumes:
      - ./api/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=test
      # ### ИЗМЕНЕНИЕ: Используем основную БД, т.к. тесты должны работать в транзакциях ###
      - DATABASE_URL=postgresql://user:password@db:5432/mutabor?schema=public
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mutabor
    command: npm run test

  db: # Сервис базы данных PostgreSQL
    image: postgres:13
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutabor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mutabor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data: