services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: mutabor_dev_client
    ports:
      - "8080:3000"
    depends_on:
      api:
        condition: service_started
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: mutabor_dev_api
    ports:
      - "8081:3001"
    depends_on:
      db_dev:
        condition: service_healthy
    env_file:
      - ./api/.env.dev
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_HOST=db_dev
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mutabor_dev
      - DATABASE_URL=postgresql://user:password@db_dev:5432/mutabor_dev?schema=public
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/dist
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s

  db_dev:
    image: postgres:13
    container_name: mutabor_dev_db
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutabor_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mutabor_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_dev_data: