version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15
    container_name: mutabor_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      # Важно: эти данные будут использоваться в DATABASE_URL
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutabor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # Volume для сохранения данных БД между перезапусками контейнера
  postgres_data: