// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwhrqflnqwayemqgoqeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aHJxZmxucXdheWVtcWdvcWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODA3MTksImV4cCI6MjA2NTU1NjcxOX0.XYOUMozkBofJ9MNkjx4LEZa4PeHTWI-DZSGt1I-sKb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);