# api/Dockerfile.dev
FROM node:20-bullseye-slim

RUN apt-get update && apt-get install -y \
    curl \
    default-jre-headless \
    unzip \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/liquibase \
    && curl -L https://github.com/liquibase/liquibase/releases/download/v4.28.0/liquibase-4.28.0.zip -o liquibase.zip \
    && unzip liquibase.zip -d /usr/local/liquibase \
    && rm liquibase.zip \
    && chmod +x /usr/local/liquibase/liquibase
ENV PATH="/usr/local/liquibase:${PATH}"

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# ### ИЗМЕНЕНИЕ: Добавлен запуск `npm run seed` после миграций
CMD ["sh", "-c", "liquibase --url=\"jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}\" --username=\"${DB_USER}\" --password=\"${DB_PASSWORD}\" update && npm run seed && npm run start:dev"]